version: '2'

services:
  config-db:
    build:
      context: .
      dockerfile: db.Dockerfile
    volumes:
      - db-datavolume:/data/db

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - '80:80'
    depends_on:
      - "config-db"

volumes:
  db-datavolume:
