version: '2'

services:
  config-db:
    image: lnls/docker-config-db-service:mongo
    volumes:
      - db-datavolume:/data/db

  api:
    image: lnls/docker-config-db-api:mongo
    ports:
      - '8085:80'
    depends_on:
      - "config-db"

volumes:
  db-datavolume:
